//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E4425.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        public int CustomerId { get; set; }
        [Required(ErrorMessage = "Customer cannot be empty")]
        public string CustomerName { get; set; }
        [Required(ErrorMessage = "Country should be chosen")]
        public Nullable<int> CountryId { get; set; }
        [Required(ErrorMessage = "City should be chosen")]
        public Nullable<int> CityId { get; set; }

        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
    }
}
